name: Unit Testing

on:
  pull_request:
    branches:
      - dev
    paths:
      - '**/*.py'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      
    - name: Run unit tests
      run: python -m unittest test.py
